---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zilla
spec:
  releaseName: zilla
  targetNamespace: kube-system
  chart:
    spec:
      chart: zilla
      sourceRef:
        kind: HelmRepository
        name: zilla
        namespace: flux-system
      version: "^0.9.55"
  interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: zilla-values
