apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: observer
spec:
  selector:
    matchLabels:
      name: observer
  template:
    metadata:
      labels:
        name: observer
    spec:
      imagePullSecrets:
        - name: container-registry-auth
      containers:
        - name: pixie
          image: ghcr.io/orbservability/pixie:6566889c-dffdb3b
          env:
            - name: PL_STIRLING_SOURCES
              value: "kAll"
          securityContext:
            privileged: true
        - name: observer-network-stats
          image: ghcr.io/orbservability/observer:main-adfcd1a-1701284908
          volumeMounts:
            - name: network-stats-volume
              mountPath: /usr/src/app/config
        - name: observer-process-stats
          image: ghcr.io/orbservability/observer:main-adfcd1a-1701284908
          volumeMounts:
            - name: process-stats-volume
              mountPath: /usr/src/app/config
        - name: observer-http-events
          image: ghcr.io/orbservability/observer:main-adfcd1a-1701284908
          volumeMounts:
            - name: http-events-volume
              mountPath: /usr/src/app/config
      volumes:
        - name: network-stats-volume
          configMap:
            name: pxl-network-stats-cm
        - name: process-stats-volume
          configMap:
            name: pxl-process-stats-cm
        - name: http-events-volume
          configMap:
            name: pxl-http-events-cm

      hostNetwork: true
      priorityClassName: system-node-critical
