---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pixie
spec:
  releaseName: pixie
  targetNamespace: pl
  chart:
    spec:
      chart: vizier-chart
      sourceRef:
        kind: HelmRepository
        name: pixie
        namespace: flux-system
      version: "^0.1.4"
  interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: pixie-values
