---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd.yaml
  - release.yaml
  - redpanda.yaml
configMapGenerator:
  - name: redpanda-controller-values
    files:
      - values.yaml=values.yaml
components:
  - ../../components/configurations
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: redpanda-ns-ts
      namespace: flux-system
    unsetOnly: true
