---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd.yaml
  - release.yaml
  - redpanda.yaml
configMapGenerator:
  - name: redpanda-controller-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml
components:
  - ../../components/configurations
