---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda-controller
spec:
  releaseName: redpanda-controller
  targetNamespace: redpanda
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: redpanda
        namespace: flux-system
      version: "^0.3.11"
  interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: redpanda-controller-values
