---
apiVersion: cluster.redpanda.com/v1alpha1
kind: Topic
metadata:
  name: queries
spec:
  partitions: 3
  replicationFactor: 3
  additionalConfig:
    cleanup.policy: "compact"
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.redpanda.svc.cluster.local:9093"
      - "redpanda-1.redpanda.redpanda.svc.cluster.local:9093"
      - "redpanda-2.redpanda.redpanda.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"

---
apiVersion: cluster.redpanda.com/v1alpha1
kind: Topic
metadata:
  name: commands
spec:
  partitions: 3
  replicationFactor: 3
  additionalConfig:
    cleanup.policy: "compact"
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.redpanda.svc.cluster.local:9093"
      - "redpanda-1.redpanda.redpanda.svc.cluster.local:9093"
      - "redpanda-2.redpanda.redpanda.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"

---
apiVersion: cluster.redpanda.com/v1alpha1
kind: Topic
metadata:
  name: replies
spec:
  partitions: 3
  replicationFactor: 3
  additionalConfig:
    cleanup.policy: "compact"
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.redpanda.svc.cluster.local:9093"
      - "redpanda-1.redpanda.redpanda.svc.cluster.local:9093"
      - "redpanda-2.redpanda.redpanda.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"
