---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: emojivoto
spec:
  interval: 10m
  url: https://github.com/BuoyantIO/emojivoto
  ref:
    branch: main

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emojivoto
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: emojivoto
    namespace: flux-system
  targetNamespace: emojivoto
  path: ./kustomize/deployment
  prune: true
  wait: true
  timeout: 5m
